src/Entity/Boxeur.php
<?php

namespace App\Entity;

use App\Repository\BoxeurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BoxeurRepository::class)]
class Boxeur
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Nom = null;

    #[ORM\Column(length: 255)]
    private ?string $Prenom = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Pseudo = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $Date_naissance = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $Description = null;

    #[ORM\Column(length: 255)]
    private ?string $Activite = null;

    #[ORM\Column]
    private ?int $Victoire = null;

    #[ORM\Column]
    private ?int $Defaite = null;

    #[ORM\Column]
    private ?int $Egalite = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $image = null;

    /**
     * @var Collection<int, Pratique>
     */
    #[ORM\OneToMany(targetEntity: Pratique::class, mappedBy: 'Boxeur')]
    private Collection $pratiques;


    /**
     * @var Collection<int, Obtenir>
     */
    #[ORM\OneToMany(targetEntity: Obtenir::class, mappedBy: 'Boxeur')]
    private Collection $obtenirs;

    /**
     * @var Collection<int, Peser>
     */
    #[ORM\OneToMany(targetEntity: Peser::class, mappedBy: 'Boxeur')]
    private Collection $pesers;

    /**
     * @var Collection<int, Commentaire>
     */
    #[ORM\OneToMany(targetEntity: Commentaire::class, mappedBy: 'Boxeur')]
    private Collection $commentaires;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $resume = null;




    public function __construct()
    {
        $this->pratiques = new ArrayCollection();
        $this->obtenirs = new ArrayCollection();
        $this->pesers = new ArrayCollection();
        $this->commentaires = new ArrayCollection();

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): static
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): static
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getPseudo(): ?string
    {
        return $this->Pseudo;
    }

    public function setPseudo(?string $Pseudo): static
    {
        $this->Pseudo = $Pseudo;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->Date_naissance;
    }

    public function setDateNaissance(\DateTimeInterface $Date_naissance): static
    {
        $this->Date_naissance = $Date_naissance;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): static
    {
        $this->Description = $Description;

        return $this;
    }

    public function getActivite(): ?string
    {
        return $this->Activite;
    }

    public function setActivite(string $Activite): static
    {
        $this->Activite = $Activite;

        return $this;
    }

    public function getVictoire(): ?int
    {
        return $this->Victoire;
    }

    public function setVictoire(int $Victoire): static
    {
        $this->Victoire = $Victoire;

        return $this;
    }

    public function getDefaite(): ?int
    {
        return $this->Defaite;
    }

    public function setDefaite(int $Defaite): static
    {
        $this->Defaite = $Defaite;

        return $this;
    }

    public function getEgalite(): ?int
    {
        return $this->Egalite;
    }

    public function setEgalite(int $Egalite): static
    {
        $this->Egalite = $Egalite;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): static
    {
        $this->image = $image;

        return $this;
    }

    /**
     * @return Collection<int, Pratique>
     */
    public function getPratiques(): Collection
    {
        return $this->pratiques;
    }

    public function addPratique(Pratique $pratique): static
    {
        if (!$this->pratiques->contains($pratique)) {
            $this->pratiques->add($pratique);
            $pratique->setBoxeur($this);
        }

        return $this;
    }

    public function removePratique(Pratique $pratique): static
    {
        if ($this->pratiques->removeElement($pratique)) {
            // set the owning side to null (unless already changed)
            if ($pratique->getBoxeur() === $this) {
                $pratique->setBoxeur(null);
            }
        }

        return $this;
    }


    /**
     * @return Collection<int, Obtenir>
     */
    public function getObtenirs(): Collection
    {
        return $this->obtenirs;
    }

    public function addObtenir(Obtenir $obtenir): static
    {
        if (!$this->obtenirs->contains($obtenir)) {
            $this->obtenirs->add($obtenir);
            $obtenir->setBoxeur($this);
        }

        return $this;
    }

    public function removeObtenir(Obtenir $obtenir): static
    {
        if ($this->obtenirs->removeElement($obtenir)) {
            // set the owning side to null (unless already changed)
            if ($obtenir->getBoxeur() === $this) {
                $obtenir->setBoxeur(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Peser>
     */
    public function getPesers(): Collection
    {
        return $this->pesers;
    }

    public function addPeser(Peser $peser): static
    {
        if (!$this->pesers->contains($peser)) {
            $this->pesers->add($peser);
            $peser->setBoxeur($this);
        }

        return $this;
    }

    public function removePeser(Peser $peser): static
    {
        if ($this->pesers->removeElement($peser)) {
            // set the owning side to null (unless already changed)
            if ($peser->getBoxeur() === $this) {
                $peser->setBoxeur(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Commentaire>
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): static
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires->add($commentaire);
            $commentaire->setBoxeur($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): static
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getBoxeur() === $this) {
                $commentaire->setBoxeur(null);
            }
        }

        return $this;
    }

    public function getResume(): ?string
    {
        return $this->resume;
    }

    public function setResume(string $resume): static
    {
        $this->resume = $resume;

        return $this;
    }



}

src/Entity/Commentaire.php
<?php

namespace App\Entity;

use App\Repository\CommentaireRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommentaireRepository::class)]
class Commentaire
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $Contenu = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $Date_commentaire = null;

    #[ORM\ManyToOne(inversedBy: 'commentaires')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Boxeur $Boxeur = null;

    #[ORM\ManyToOne(inversedBy: 'commentaires')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $User = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContenu(): ?string
    {
        return $this->Contenu;
    }

    public function setContenu(string $Contenu): static
    {
        $this->Contenu = $Contenu;

        return $this;
    }

    public function getDateCommentaire(): ?\DateTimeInterface
    {
        return $this->Date_commentaire;
    }

    public function setDateCommentaire(\DateTimeInterface $Date_commentaire): static
    {
        $this->Date_commentaire = $Date_commentaire;

        return $this;
    }

    public function getBoxeur(): ?Boxeur
    {
        return $this->Boxeur;
    }

    public function setBoxeur(?Boxeur $Boxeur): static
    {
        $this->Boxeur = $Boxeur;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): static
    {
        $this->User = $User;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_PSEUDO', fields: ['Pseudo'])]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $Pseudo = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $Nom = null;

    #[ORM\Column(length: 255)]
    private ?string $Prenom = null;

    #[ORM\Column(length: 255)]
    private ?string $Email = null;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private ?string $resetToken = null;

    /**
     * @var Collection<int, Commentaire>
     */
    #[ORM\OneToMany(targetEntity: Commentaire::class, mappedBy: 'User')]
    private Collection $commentaires;

    public function __construct()
    {
        $this->commentaires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPseudo(): ?string
    {
        return $this->Pseudo;
    }

    public function setPseudo(string $Pseudo): static
    {
        $this->Pseudo = $Pseudo;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->Pseudo;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): static
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): static
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): static
    {
        $this->Email = $Email;

        return $this;
    }

    public function getResetToken(): ?string
    {
        return $this->resetToken;
    }

    public function setResetToken(?string $resetToken): self
    {
        $this->resetToken = $resetToken;

        return $this;
    }

    /**
     * @return Collection<int, Commentaire>
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): static
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires->add($commentaire);
            $commentaire->setUser($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): static
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getUser() === $this) {
                $commentaire->setUser(null);
            }
        }

        return $this;
    }
}

src/Controller/guest/BoxeAnglaiseController.php
<?php

declare(strict_types=1);

namespace App\Controller\guest;

use App\Entity\Commentaire;
use App\Entity\TypeBoxe;
use App\Form\CommentaireType;
use App\Repository\CategorieRepository;
use App\Repository\CommentaireRepository;
use App\Repository\PratiqueRepository;
use App\Repository\TypeBoxeRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use App\Repository\BoxeurRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class BoxeAnglaiseController extends AbstractController
{

    #[Route('/boxe-anglaise', 'home_boxe_anglaise')]
    public function boxeAnglaise(BoxeurRepository $boxeurRepository, TypeBoxeRepository $typeBoxeRepository)
    {

        $typeBoxe = $typeBoxeRepository->findOneById(1);

        if ($typeBoxe) {
            $boxeurs = $boxeurRepository->findByTypeBoxe($typeBoxe);

            return $this->render('guest/anglaise/anglaise.html.twig', [
                'boxeurs' => $boxeurs,
                'typeBoxe' => $typeBoxe
            ]);
        }
        return $this->render('guest/404.html.twig');
    }


    #[Route('/boxe-anglaise/superplumes', 'boxe_anglaise_superplumes')]
    public function boxeAnglaise57(BoxeurRepository $boxeurRepository, CategorieRepository $categorieRepository, TypeBoxeRepository $typeBoxeRepository): Response
    {
        $typeBoxe = $typeBoxeRepository->findOneById(1);
        $category = $categorieRepository->findOneById(1);

        if ($typeBoxe && $category) {
            $boxeurs = $boxeurRepository->findByTypeAndCategory($typeBoxe, $category);
        }
        return $this->render('guest/anglaise/anglaiseSuperPlumes.html.twig', [
            'category' => $category,
            'boxeurs' => $boxeurs,
            'typeBoxe' => $typeBoxe
        ]);
    }



    #[Route('/boxe-anglaise/superlourd', 'boxe_anglaise_superlourd')]
    public function boxeAnglaise64(BoxeurRepository $boxeurRepository, CategorieRepository $categorieRepository, TypeBoxeRepository $typeBoxeRepository): Response
    {
        $typeBoxe = $typeBoxeRepository->findOneById(1);
        $category = $categorieRepository->findOneById(2);

        if ($typeBoxe && $category) {
            $boxeurs = $boxeurRepository->findByTypeAndCategory($typeBoxe, $category);
        }
        return $this->render('guest/anglaise/anglaiseSuperLourds.html.twig', [
            'category' => $category,
            'boxeurs' => $boxeurs,
            'typeBoxe' => $typeBoxe
        ]);

    }


    #[Route('/show-boxeur/{id}', name: 'show_boxeur')]
    public function showBoxeur(int $id, BoxeurRepository $boxeurRepository,Request $request, EntityManagerInterface $entityManager,CommentaireRepository $commentaireRepository):Response
    {
        $boxeur = $boxeurRepository->find($id);

        if (!$boxeur) {
            $html404 = $this->renderView('guest/404.html.twig');
            return new Response($html404, 404);
        }

        // Récupérer l'utilisateur connecté
        $user = $this->getUser();

        $commentaire = new Commentaire();
        $commentaire->setBoxeur($boxeur);
        $commentaire->setUser($user);
        $commentaire->setDateCommentaire(new \DateTime());

        // Créer le formulaire de commentaire
        $form = $this->createForm(CommentaireType::class, $commentaire);
        $form->handleRequest($request);

        // Si le formulaire est soumis et valide
        if ($form->isSubmitted() && $form->isValid()) {

            $entityManager->persist($commentaire);
            $entityManager->flush();

            // Redirection pour éviter la double soumission
            return $this->redirectToRoute('show_boxeur', ['id' => $boxeur->getId()]);
        }

        $commentaires = $commentaireRepository->findBy(['Boxeur' => $boxeur]);



        return $this->render('guest/showBoxeur.html.twig', [
            'boxeur' => $boxeur,
            'commentaires' => $commentaires,
            'form' => $form->createView()
        ]);
    }

}

templates/guest/404.html.twig
{% extends 'guest/base.html.twig' %}


{% block body %}
    <p>test</p>
{% endblock %}

templates/guest/index.html.twig
{% extends 'guest/base.html.twig' %}

{# ------------- TITRE PAGE ------------- #}

    {% block title %}
        Best's Boxer : Page d'Accueil
    {% endblock %}

{# ------------- BODY ------------- #}

        {% block body %}
            {# ------------- CAROUSSEL ------------- #}
            <section class="marginCaroussel">
                <div class="owl-carousel">
                    {% for boxeur in boxeurs %}
                        <div>
                            <img src="{{ asset('assets/uploads/'~boxeur.image) }}" alt="image de {{ boxeur.nom }}" />
                        </div>
                    {% endfor %}
                </div>
            </section>

            {# ------------- TITRE H1 ------------- #}
            <h1 id="titleHome" class="font">Derniers Articles </h1>
            <section class="w78 font">
                <div>
                    {% if randomBoxeurs is not empty %}
                    <div class="Tablette">
                        {% for boxeur in randomBoxeurs %}
                            <article class="paddArticles flex littleMarginBot w48">
                                <div class="DivImgArticles">
                                    <img src="{{ asset('assets/uploads/'~boxeur.image) }}" alt="Image de {{ boxeur.nom }}"/>
                                </div>
                                {# ------------- Text Article ------------- #}
                                <div class="flex2 bcgBlue paddArticles shadow translate radius">
                                    <h2 class="nameBox white center paddArticles10px">{{ boxeur.prenom }} {{ boxeur.nom }}</h2>
                                    <p class="white paddArticles10px">
                                        {{ boxeur.resume }}
                                    </p>
                                    {# ------------- En Savoir Plus ------------- #}
                                    <a id="ancreBlue" class="center dblock paddArticles10px" href="{{ path('show_boxeur', {id:boxeur.id}) }}">En savoir plus</a>
                                </div>
                            </article>
                        {% endfor %}
                    </div>
                    {% endif %}
                    {# <div class="w50 apiBoxeurs">
                        <h2>Boxeurs de l'API</h2>
                        <ul>
                            {% for apiBoxeur in apiBoxeurs %}
                                <li class="boxeur-item">
                                    <h3>{{ apiBoxeur.name }}</h3>
                                    <p><strong>Nationalité :</strong> {{ apiBoxeur.nationality }}</p>
                                    <p><strong>Record :</strong> {{ apiBoxeur.record }}</p>
                                    <p><strong>Classement :</strong> {{ apiBoxeur.rank }}</p>
                                </li>
                            {% else %}
                                <p>Aucun boxeur disponible pour le moment depuis l'API.</p>
                            {% endfor %}
                        </ul>
                    </div> #}
                </div>
            </section>

        {% endblock %}
        {% block javascript %}
        <script
            src="https://code.jquery.com/jquery-3.7.1.min.js"
            integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo="
            crossorigin="anonymous">
        </script>
        <script src="{{ asset('assets/js/OwlCaroussel/owl.carousel.min.js') }}"></script>
        <script>
            $(document).ready(function(){
                $(".owl-carousel").owlCarousel({
                    loop:true,
                    autoplay:true,
                    center: true,
                    autoplayTimeout:2000,
                    autoplayHoverPause:true,
                    responsive:{
                        0:{
                            items: 2
                        },
                        780:{
                            items: 2
                        },
                        1025:{
                            items: 3
                        }
                    }
                });
        });
        </script>
    {% endblock %}

templates/guest/inscription.html.twig
{% extends 'guest/base.html.twig' %}

{# ------------- TITRE PAGE ------------- #}

    {% block title %}
        Best's Boxer : Inscription
    {% endblock %}

{# ------------- BODY ------------- #}

        {% block body %}
            <section class="font w50">
                <h1 class="center inscription">Inscription</h1>

                {{ form_start(userForm) }}
                {# EMAIL #}
                <div class="padd11px">
                    {{ form_label(userForm.Email) }}
                    {{ form_widget(userForm.Email) }}
                    {{ form_errors(userForm.Email) }}
                </div>
                {# PASSWORD #}
                <div class="padd11px">
                    {{ form_widget(userForm.password) }}
                    {{ form_errors(userForm.password) }}
                </div>
                {# PRENOM #}
                <div class="padd11px">
                    {{ form_label(userForm.Prenom) }}
                    {{ form_widget(userForm.Prenom) }}
                    {{ form_errors(userForm.Prenom) }}
                </div>
                {# NOM #}
                <div class="padd11px">
                    {{ form_label(userForm.Nom) }}
                    {{ form_widget(userForm.Nom) }}
                    {{ form_errors(userForm.Nom) }}
                </div>
                {# PSEUDO #}
                <div class="padd11px">
                    {{ form_label(userForm.Pseudo) }}
                    {{ form_widget(userForm.Pseudo) }}
                    {{ form_errors(userForm.Pseudo) }}
                </div>
                {{ form_end(userForm) }}
            </section>
        {% endblock %}

templates/guest/showBoxeur.html.twig
{% extends 'guest/base.html.twig' %}

{# ------------- TITRE PAGE ------------- #}

    {% block title %}
        Best's Boxer : Boxe Anglaise
    {% endblock %}

{# ------------- BODY ------------- #}

        {% block body %}
            <section class="w90flex wrap">
                    <article class="w45 font">
                        {# ------------- IMG Articles ------------- #}
                        <div class="marginTop">
                            <img src="{{ asset('assets/uploads/'~boxeur.image) }}" alt="image de {{ boxeur.nom }}" />
                        </div>
                        {# ------------- RESULT ------------- #}
                        <div class="result">
                            <p class="center">
                                <span class="beigeChaud">W :</span> <span class="white">{{ boxeur.victoire }}</span>
                            </p>
                            <p class="center">
                                <span class="beigeChaud">L :</span> <span class="white">{{ boxeur.defaite }}</span>
                            </p>
                            <p class="center">
                                <span class="beigeChaud">D :</span> <span class="white">{{ boxeur.egalite }}</span>
                            </p>
                        </div>
                        {# ------------- Text Article ------------- #}
                        <div class="paddArtBoxeAng">
                            <h2 class="center beigeChaud">{{ boxeur.prenom }} {{ boxeur.nom }}</h2>
                            <p class="paddArtBoxeAng center">
                                {{ boxeur.description }}
                            </p>
                        </div>
                    </article>
            </section>

            <section class="font w50">
            <h3 class="center padd10px beigeChaud littleMarginBot fontSize">Commentaires</h3>

            {# Liste des commentaires #}
            {% if commentaires is not empty %}
                <div>
                    {% for commentaire in commentaires %}
                        <div class="flexComment">
                            <div class="w30 padd10px">
                                <p><span class="spanComment">{{ commentaire.user.Pseudo }}</span></p><p class="littleCarac">le {{ commentaire.dateCommentaire|date('d/m/Y H:i') }} :</p>
                            </div>
                            <div class="w70 padd10px">
                                <p>{{ commentaire.contenu }}</p>
                            </div>
                        </div>
                        <hr>
                    {% endfor %}
                </div>
            {% else %}
                <p class="center">Il n'y a pas encore de commentaires sur ce boxeur.</p>
            {% endif %}

            {# Formulaire de commentaire #}
            <h3 class="center padd10px beigeChaud heavyMarginTop fontSize">Ajouter un commentaire</h3>
            {% if app.user %}
                <div class="center littleMarginBot">
                    {{ form_start(form) }}
                    {{ form_row(form.Contenu, {'label': false}) }}
                    {{ form_row(form.submit) }}
                    {{ form_end(form) }}
                </div>
            {% else %}
                <p class="center padd10px">Veuillez vous <a class="ancreBoxeAng underline" href="{{ path('app_login') }}">connecter</a> afin d'ajouter un commentaire.</p>
            {% endif %}
            </section>

        {% endblock %}